# Generated by Django 4.1.1 on 2022-10-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='alamat',
        ),
    ]
