# Generated by Django 4.1.1 on 2022-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_remove_mahasiswa_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='foto',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
